name: ChatOps
on: issue_comment # this is used for PRs https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  MAGIC_COMMENT: "/wandb" # this is a parameter you can change

jobs:
  see-comment:
    # this filters for only comments made on a pull request
    if: (github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
    - name: see payload # this step is for debugging purposes only, so you can see the payload. 
      run: echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
        
    - name: filter for magic comment
      id: filter
      if: contains(github.event.comment.body, env.MAGIC_COMMENT)
      run: echo "magic comment detected"
      
    - name: Parse value from the magic command
      if: steps.filter.outcome == 'success'
      id: get-magic-value
      run: |
        const comment = process.env.PR_COMMENT || '';
        const magicComment = process.env.MAGIC_COMMENT;
        const regex = new RegExp(`${magicComment}\\s+(\\S+)`);
        const match = comment.match(regex);
        if (match) {
          console.log(`::set-output name=VAL_FOUND::true`);
          console.log(`::set-output name=MAGIC_VAL::${match[1]}`);
        } else {
          console.log(`::set-output name=VAL_FOUND::false`);
        }
      env:
        PR_COMMENT: ${{ github.event.comment.body }}
        MAGIC_COMMENT: ${{ env.MAGIC_COMMENT }}
        
    - name: print value of magic command
      if:  steps.get-magic-value.outcome == 'success' && steps.get-magic-value.outputs.VAL_FOUND == 'true'
      run: echo "the value is ${{ steps.get-magic-value.outputs.MAGIC_VAL }}"
      
    - name: Make a comment with the GitHub API
      uses: actions/github-script@v6
      if: steps.get-magic-value.outcome == 'success' 
      with:
        script: |
           var msg = `👋 Hello!  You commented on this PR with a magic value of \`${process.env.MAGIC_VAL}\``;
           github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            });
      env:
        MAGIC_VAL: "${{ steps.get-magic-value.outputs.MAGIC_VAL }}"